version: '3'

services:
  shinyapp:
    platform: linux/x86_64
    image: shiny_app_image:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6868:6868"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.masldatlas.entrypoints=websecure"
      - "traefik.http.routers.masldatlas.rule=Host(`masldatlas.scilicium.com`)"
      - "traefik.http.services.masldatlas.loadbalancer.server.port=6868"
    volumes:
      - ./data/datasets:/shinyApp/datasets
      - ./data/enrichment_sets:/shinyApp/enrichment_sets
    container_name: MASLDAtlas
    networks:
      - web
    restart: always

networks:
  web:
    external: true
